config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :employee, ->(emp) { emp.super_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end
  resources :donation_services
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :employees do
    resources :contributions
    resources :claims
    resources :jobs
    resources :elections do
      post 'vote', to: 'elections#vote'
      patch 'vote', to: 'elections#vote'
      post 'veto', to: 'elections#veto'
    end

    get 'show_admin', to: 'employees#show_admin'
    get 'admin_profile', to: 'employees#admin_profile'
    post 'dismiss_notifications', to: 'employees#dismiss_notifications'
  end

  # static pages
  get 'about', to: 'static_pages#about'

  root to: redirect('about')
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  ADDITIONAL_INFO = %w[address1 zip phone].freeze

  has_many :contributions, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :claims, dependent: :destroy
  has_one_attached :avatar
  enum occupation: { 'porter' => 0, 'guide' => 1, 'cook' => 2,
                     'head_guide' => 3, 'chairman' => 4, 'secretary' => 5, 'spokesman' => 6, 'treasurer' => 7 },
       _default: 'porter'
  enum role: { 'contributor' => 0, 'member' => 1, 'admin' => 2, 'super_admin' => 3 }, _default: 'contributor'
  validates :email, uniqueness: { case_sensitive: false }
  validates :id, uniqueness: { allow_blank: true }
  validates :first_name, :last_name, presence: true
  validates :phone, phone: { message: 'incorrect phone number format. Please include country code
  and phone number exp: +255 750995366', allow_blank: true }
  validates :phone, uniqueness: { message: 'phone number already in use by another user', allow_blank: true } # rubocop:disable Rails/UniqueValidationWithoutIndex
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  before_create { first_name.downcase! and last_name.downcase! }
  before_update { first_name.downcase! and last_name.downcase! }

  pay_customer

  def latest_contribution_date
    contributions.order(:created_at).pluck(:created_at).last or 200.years.ago
  end

  def latest_job_date
    jobs.order(:date_completed).pluck(:date_completed).last or 200.years.ago
  end

  def votable_employees
    # force evaluation for all employees.
    Employee.where('role > ?', Employee.roles[:contributor]).where.not(id: self) || []
  end

  def role
    # anyone with privileges admin privileges and above
    return self[:role] if Employee.roles[self[:role]] >= Employee.roles[:admin]

    if jobs.count >= Config.min_jobs.fetch &&
       contributions.count >= Config.min_contributions.fetch &&
       latest_contribution_date >= Config.latest_contribution.fetch.ago &&
       latest_job_date >= Config.latest_job.fetch.ago

      update(role: 'member')
      return 'member'
    end
    update(role: 'contributor')
    'contributor'
  end

  def unintialized_attrs
    # address2 not included as it is not always required
    attributes.select { |k, v| v.nil? and Employee::ADDITIONAL_INFO.include? k }.keys
  end

  # for pay compatibility
  def name
    "#{first_name.humanize} #{last_name.humanize}"
  end

  def pay_customer_name
    name
  end

  def privileged?
    Employee.roles[role] >= Employee.roles['member']
  end

  def admin?
    Employee.roles[role] >= Employee.roles['admin']
  end
end

app/controllers/employees/registrations_controller.rb
# frozen_string_literal: true

module Employees
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]
    before_action :editable
    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    def account_update_params
      employee_attrs = %i[ first_name last_name phone address1
                           address2 zip password_confirmation current_password password ]
      devise_parameter_sanitizer.permit(:account_update, keys: employee_attrs)
      super
    end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    def after_update_path_for(resource)
      employee_path resource
    end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
    private

    def editable
      return if [params.fetch(:id, ''), params.fetch(:format, '')].include? current_employee.id.to_s

      flash[:danger] = "can't edit another employees information"
      redirect_to :root
    end
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :set_employee
  before_action :authenticate_employee!
  before_action :set_election_notifications
  before_action :admin_only, only: %i[admin_profile index]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  def show; end

  def show_admin
    if AdminElection.current_admin.present?
      @employee = AdminElection.current_admin
      @previous_terms = AdminElection.elections_won(@employee)
      @terms_ends = AdminElection.latest_election.ends_at
    else
      flash[:info] = 'there currently is no admin, this means they have either been vetoed or an election is ongoing'
    end
  end

  def admin_profile
    redirect_to action: :index, method: :get if flash[:error]
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = (params[:id] and Employee.find(params[:id])) or current_employee
  end

  # Only allow a list of trusted parameters through.
  def employee_params
    return unless params[:employee]

    params.require(:employee).permit(:first_name, :last_name, :role, :contributions, :email,
                                     :occupation)
  end

  def set_election_notifications
    @pending_elections = Election.pending_elections(current_employee)
  end

  def admin_only
    return if set_employee.admin?

    flash[:danger] = 'Must be an admin'
    redirect_to :root
  end
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
  def default_image
    'https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg'
  end

  def all_occupations
    Employee.occupations.keys
  end

  def present_election(election)
    election.type.gsub(/election/i, '').humanize
  end

  def profile_pic(employee)
    employee.avatar.attached? ? employee.avatar : default_image
  end

  def submit_text(edit_enabled)
    edit_enabled ? 'Edit' : 'Edit Profile'
  end

  def occupation_dropdown
    all_occupations.map { |e| [e.humanize, e] }
  end

  def view_contribution(contribution_date)
    # contributions are default set
    return 'no contributions made' if contribution_date < 199.years.ago

    display_time(contribution_date)
  end

  def display_arrow(param)
    param ||= 0
    case param.to_i
    when 1
      '↑'
    when 2
      '↓'
    else
      ''
    end
  end
end

app/views/employees/_additional_info_notifs.html.erb
<% missing_attrs = employee.unintialized_attrs %>

<% unless missing_attrs.empty? %>
    <div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Missing additional info:</h4>
    <p>You are missing some additional info. Certain features might be incomplete or might not work because the following attributes are missing
    </p>
    <hr>
    <p> Please fill the following fields out at your earliest convenience </p>
    <ul>
        <% missing_attrs.each do |missing| %>
            <li><%= link_to missing, edit_employee_path(employee), class: 'alert-link' %></li>
        <% end %>
    </ul>
    <%= button_to 'Dismiss', employee_dismiss_notifications_path(employee), class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/employees/_election_notifications.html.erb
<% unless @pending_elections.empty? %>
  <div class="alert alert-warning">
    <h6>Election Reminder</h6>
    <p>You still need to vote in the following elections:</p>
    <hr>
    <ul>
      <% @pending_elections.each do |election| %>
        <li>
          <%= link_to present_election(election), employee_election_path(current_employee, election) %>
          <%= "ends at #{display_time(election.ends_at)}" %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, class: 'col-form-label' %>
    <%= form.text_field :first_name, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :last_name, class: 'col-form-label' %>
    <%= form.text_field :last_name, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :email, class: 'col-form-label' %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :occupation, class: 'col-form-label' %>
    <%= form.text_field :occupation, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/_profile.html.erb
<% # args -> employee: Employee, edit_enabled: bool, path: str, method: symb %>

<div class="container rounded mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
            <img class="rounded-circle mt-5" width="150px" src="<%= profile_pic(employee) %>">
              <span class="font-weight-bold">
                <%= employee.last_name.capitalize %>
              </span>
              <span class="text-black-50">
                <%= employee.email %>
              </span>
              <span></span>
            </div>

        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div>
                <%= form_with(model: employee, url: path, method: method) do |f| %>
                <% if employee.errors.any? %>
                  <div id="error_explanation" class="alert alert-danger">
                    <h4><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being edited</h4>
                    <hr/>
                    <ul>
                      <% employee.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <div class="row mt-2">
                    <div class="col-md-6">
                        <%= f.label :first_name, 'Name' , class: 'labels' %>
                        <%= f.text_field :first_name, class: 'form-control', value: employee.first_name.humanize, disabled: !edit_enabled %>
                    </div>
                    <div class="col-md-6">
                        <%= f.label :last_name, 'Surname', class: 'labels' %>
                        <%= f.text_field :last_name, class: 'form-control', value: employee.last_name.humanize, disabled: !edit_enabled %>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12">
                      <%= f.label :occupation, 'Main Occupation', class: 'labels' %>
                      <% if edit_enabled %>
                        <%= f.select :occupation, occupation_dropdown, class: 'form-control' %>
                      <% else %>
                        <%= f.text_field :occupation, class: 'form-control', value: employee.occupation.humanize, disabled: true %>
                      <% end %>

                    </div>
                    <div class="col-md-12">
                        <%= f.label :phone, 'Mobile Number (format: +255 750995366)', class: 'labels' %>
                        <%= f.telephone_field :phone, class: 'form-control', value: employee.phone, disabled: !edit_enabled %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :address1, 'Address Line 1', class: 'labels' %>
                        <%= f.text_field :address1, class: 'form-control', value: employee.address1, disabled: !edit_enabled %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :address2, 'Address Line 2', class: 'labels'%>
                        <%= f.text_field :address2, class: 'form-control', value: employee.address2, disabled: !edit_enabled %>
                    </div>
                    <div class="col-md-12">
                        <%= f.label :zip, 'Postcode', class: 'labels' %>
                        <%= f.text_field :zip, class: 'form-control', value: employee.zip, disabled: !edit_enabled %>
                    </div>
                      <%= yield f if block_given? %>
                    </div>
                    <br>
                    <div class="d-flex justify-content-center">
                      <%= f.submit(submit_text(edit_enabled), class: 'btn btn-primary') if params[:id] == current_employee.id.to_s %>
                    </div>
              <% end %>
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center experience"><span>Contribution Summary</span>
                <%= button_to 'Make new contribution', new_employee_contribution_path(employee), class: 'btn-sm btn-success', method: :get %>
                </div><br>
                <div class="col-md-12">
                <%= label_tag :total_contributions, 'total contributions', class: 'labels' %>
                <%= text_field_tag :total_contributions, employee.contributions.count, class: 'form-control', disabled: true %>
                <br>
                <div class="col-md-12">
                <%= label_tag :latest_contribution, 'latest contribution', class: 'labels' %>
                <%= text_field_tag :latest_contribution, view_contribution(employee.latest_contribution_date), class: 'form-control', disabled: true %>
                </div>
                <div class="col-md-12">
                <%= label_tag :role, 'Role', class: 'labels' %>
                <%= text_field_tag :role, employee.role.to_s.humanize, class: 'form-control', disabled: true %>
                  <br>
                </div>
                  <div class="d-flex flex-lg-row justify-content-around">
                    <%= button_to('View Admin Info', employee_show_admin_path(employee),
                                  class: 'btn btn-outline-primary btn-lg btn-block',
                                  method: :get) if params[:id] == current_employee.id.to_s
                    %>
                    <%= button_to('View Elections', employee_elections_path(employee),
                                  class: 'btn btn-outline-primary btn-lg btn-block',
                                  method: :get) if params[:id] == current_employee.id.to_s
                    %>
                  </div>



        </div>
    </div>
</div>
</div>
</div>

<!-- credit: https://bbbootstrap.com/snippets/bootstrap-5-myprofile-90806631 -->

app/views/employees/admin_profile.html.erb
Hello, World

app/views/employees/index.html.erb
<div>
    <table id="table" class="table">
        <thead>
            <th scope="col"> Name </th>
            <th scope="col"> Role </th>
            <th scope="col"> Total Contributions </th>
            <th scope="col"> Total Jobs </th>
        </thead>
        <tbody>
            <% @employees.each do |employee| %>
            <tr>
                <td> <%= link_to employee.name, employee_path(employee) %> </td>
                <td> <%= employee.role.humanize %> </td>
                <td> <%= employee.contributions.count %> </td>
                <td> <%= employee.jobs.count %> </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<script>
getCellValue = (tr, idx) => tr.children[idx].innerText || tr.children[idx].textContent

comparer = (idx, asc) => (a, b) => ((v1, v2) =>
    v1 !== '' && v2 !== '' && !isNaN(v1) && !isNaN(v2) ? v1 - v2 : v1.toString().localeCompare(v2)
    )(getCellValue(asc ? a : b, idx), getCellValue(asc ? b : a, idx))

document.querySelectorAll('th').forEach(th => th.addEventListener('click', (() => {
  table = th.closest('table')
  tbody = table.querySelector('tbody')
  Array.from(tbody.querySelectorAll('tr'))
    .sort(comparer(Array.from(th.parentNode.children).indexOf(th), this.asc = !this.asc))
    .forEach(tr => tbody.appendChild(tr) )
})))

</script>

app/views/employees/new.html.erb
<%= render 'election_notifications' %>
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<%= render 'election_notifications' %>
<%= render 'profile', employee: @employee, edit_enabled: false,
 path: edit_employee_registration_path(@employee), method: :get %>

app/views/employees/show_admin.html.erb
<%= render 'election_notifications' %>

<% if @admin_elect.present? %>
  <div class="container mt-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-7">
        <div class="card p-3 py-4">
          <div class="text-center"> <img src="<%= profile_pic(@employee) %>" width="100" class="rounded-circle" alt=""> </div>
          <div class="text-center mt-3">
            <span class="bg-secondary p-1 px-4 rounded text-white">
              <%= @employee.occupation.humanize %>
            </span>
            <h5 class="mt-2 mb-0"><%= @employee.name %></h5>
            <div class="px-4 mt-1">
              <p class="fonts">
                Summary of Statistics
              </p>
            </div>
            <ul class="social-list">
              <li>
                Jobs Done: <%= @employee.jobs.count %>
              </li>
              <li>
                Contributions Made: <%= @employee.contributions.count %>
              </li>
              <li>
                Prior Terms Served: <%= @previous_terms %>
              </li>
              <li>
                Term Ends At: <%=  display_time(@terms_ends) %>
              </li>
            </ul>
            <div class="buttons"> <button class="btn btn-outline-primary px-4">Message</button>

              <% button_to  %>

              <button class="btn btn-primary px-4 ms-3">Contact</button> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<!-- credit: https://bbbootstrap.com/snippets/bootstrap-5-user-social-profile-transition-effect-79746232 -->