config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :employee, ->(emp) { emp.super_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end
  resources :donation_services
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :employees do
    resources :contributions
    resources :claims
    resources :jobs
    resources :elections do
      post 'vote', to: 'elections#vote'
      patch 'vote', to: 'elections#vote'
      post 'veto', to: 'elections#veto'
    end

    get 'show_admin', to: 'employees#show_admin'
    get 'admin_profile', to: 'employees#admin_profile'
    post 'dismiss_notifications', to: 'employees#dismiss_notifications'
  end

  # static pages
  get 'about', to: 'static_pages#about'

  root to: redirect('about')
end

app/models/claim.rb
# frozen_string_literal: true

class Claim < ApplicationRecord
  validate -> { errors.add(:amount, 'cannot claim that much') if Config.max_claim_amount.fetch < amount }

  belongs_to :employee
  has_many_attached :support

  # make claim; can only have one outstanding claim at a time
  def make; end
end

app/controllers/claims_controller.rb
# frozen_string_literal: true

class ClaimsController < ApplicationController
  before_action :set_claim, only: %i[show edit update destroy]
  before_action :authenticate_employee!

  # GET /claims or /claims.json
  def index
    @claims = current_employee.claims
  end

  # GET /claims/1 or /claims/1.json
  def show; end

  # GET /claims/new
  def new
    @claim = Claim.new
  end

  # GET /claims/1/edit
  def edit; end

  # POST /claims or /claims.json
  def create
    @claim = current_employee.claims.new(claim_params)

    if @claim.save
      redirect_to employee_claims_path(current_employee), notice: 'Claim was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /claims/1 or /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.json { render :show, status: :ok, location: @claim }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1 or /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_claim
    @claim = Claim.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def claim_params
    params.require(:claim).permit(:amount, :reason)
  end
end

app/helpers/claims_helper.rb
# frozen_string_literal: true

module ClaimsHelper
  def max_claim_amount
    Config.max_claim_amount.fetch
  end
end

app/views/claims/_form.html.erb
<%= form_with(model: claim, url: employee_claims_path(current_employee, claim)) do |form| %>
  <% if claim.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(claim.errors.count, "error") %> prohibited this vote from being submitted:</h2>
      <ul>
        <% claim.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, value: 55.0, class: 'form-control', min: 0, max: max_claim_amount, step: 0.01 %>
  </div>

  <div class="form-group">
    <%= form.label :reason, class: 'form-label' %>
    <%= form.text_field :reason, value: 'broken leg', class: 'form-control' %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/claims/edit.html.erb
<h1>Editing Claim</h1>

<%= render 'form', claim: @claim %>

<%= link_to 'Show', @claim %> |
<%= link_to 'Back', claims_path %>

app/views/claims/index.html.erb
<div class="container rounded bg-light text-dark mt-5 mb-5">
  <div class="d-flex justify-content-between">
    <h3>Claims</h3>
    <%= button_to 'make claim', new_employee_claim_path, class: 'btn btn-success', method: :get %>
  </div>
  <% if @contributions.present? %>
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>Amount</th>
        <th>Reason</th>
        <th>Date Contributed</th>
      </tr>
      </thead>

      <tbody>
      <% @claims.each do |claim| %>
        <tr>
          <td><%= claim.amount %></td>
          <td><%= claim.purpose %></td>
          <td><%= display_time(claim.created_at) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-dark" role="alert">
      you don't have any claims yet. Click
      <%= link_to 'here', new_employee_claim_path, class: 'alert-link' %>
      to make your first one.
    </div>
  <% end %>
</div>
<br>

app/views/claims/new.html.erb
<div class="container">
  <h1>New Claim</h1>

  <%= render 'form', claim: @claim %>
</div>

app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_claim_path(@claim) %> |
<%= link_to 'Back', claims_path %>