config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :employee, ->(emp) { emp.super_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end
  resources :donation_services
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :employees do
    resources :contributions
    resources :claims
    resources :jobs
    resources :elections do
      post 'vote', to: 'elections#vote'
      patch 'vote', to: 'elections#vote'
      post 'veto', to: 'elections#veto'
    end

    get 'show_admin', to: 'employees#show_admin'
    get 'admin_profile', to: 'employees#admin_profile'
    post 'dismiss_notifications', to: 'employees#dismiss_notifications'
  end

  # static pages
  get 'about', to: 'static_pages#about'

  root to: redirect('about')
end

app/models/contribution.rb
# frozen_string_literal: true

class Contribution < ApplicationRecord
  belongs_to :employee
  validates :amount, numericality:
    { less_than: Config.max_contribution_amount.fetch,
      message: "can only input a number less than #{Config.max_contribution_amount.fetch}. inputed %<value>s" }
  validate :no_recent_contribution
  validate :max_contrib_amount
  validates :purpose, presence: true
  validates :id, uniqueness: true

  private

  def no_recent_contribution
    limit = Config.max_contribution_frequency.fetch.ago
    curr_date = Employee.find(employee_id).latest_contribution_date
    return unless curr_date > limit

    errors.add :created_at,
               "can contribute again in #{Time.zone.at(curr_date - limit).strftime('%d days %H:%M:%S')}"
  end

  def max_contrib_amount
    max_amount = Config.max_contribution_amount.fetch
    errors.add :amount, "can only contribute a max of $#{max_amount}" if (amount || Float::INFINITY) > max_amount
  end
end

app/controllers/contributions_controller.rb
# frozen_string_literal: true

class ContributionsController < ApplicationController
  before_action :authenticate_employee!
  before_action :set_contribution, only: %i[show]

  VIEW_LIMIT = 100

  # GET /contributions or /contributions.json
  def index
    @contributions = current_employee.contributions.order(created_at: :desc)
    @privileged = privledged_access
    @contributions = Contribution.all if @privileged && (params[:current_employee_filter] == 'all')
  end

  # GET /contributions/1 or /contributions/1.json
  def show; end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # POST /contributions or /contributions.json
  def create
    @contribution = current_employee.contributions.create(contribution_params)
    if @contribution.persisted?
      redirect_to employee_contributions_path(current_employee), notice: 'Contribution was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def contribution_params
    params.require(:contribution).permit(:amount, :purpose)
  end

  # when a member graduates from being a contributer to a member
  # they qualify for claims fulfillment
  def privledged_access
    current_employee.role == 'member'
  end
end

app/helpers/contributions_helper.rb
# frozen_string_literal: true

module ContributionsHelper
  def max_amount
    Config.max_contribution_amount.fetch
  end
end

app/views/contributions/_form.html.erb
<%= form_with(model: contribution, url: employee_contributions_path(current_employee)) do |form| %>
  <% if contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
        <% contribution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, value: 12_000_000, class: 'form-control', min: 0, max: max_amount, step: 0.01 %>
  </div>

  <div class="form-group">
    <%= form.label :purpose, class: 'form-label' %>
    <%= form.text_field :purpose, value: 'weekly payment', class: 'form-control' %>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<div class="container rounded bg-light text-dark mt-5 mb-5">
  <div class="d-flex justify-content-between">
    <h3>Contributions</h3>
    <%= button_to 'make contribution', new_employee_contribution_path, class: 'btn btn-success', method: :get %>
  </div>
  <% if @contributions.present? %>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Amount</th>
          <th>Purpose</th>
          <th>Date Contributed</th>
        </tr>
      </thead>

      <tbody>
        <% @contributions.each do |contribution| %>
          <tr>
            <td><%= contribution.amount %></td>
            <td><%= contribution.purpose %></td>
            <td><%= display_time(contribution.created_at) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-dark" role="alert">
      you don't have any contributions yet. Click
      <%= link_to 'here', new_employee_contribution_path, class: 'alert-link' %>
      to make your first one.
    </div>
  <% end %>
</div>
<br>

app/views/contributions/new.html.erb
<div class="container">
    <h3>New Contribution</h3>
    <div>

    </div>
    <%= render 'form', contribution: @contribution %>

    <%= link_to 'Back', employee_contributions_path(current_employee) %>
</div>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @contribution.amount %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @contribution.purpose %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>