config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :employee, ->(emp) { emp.super_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end
  resources :donation_services
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  resources :employees do
    resources :contributions
    resources :claims
    resources :jobs
    resources :elections do
      post 'vote', to: 'elections#vote'
      patch 'vote', to: 'elections#vote'
      post 'veto', to: 'elections#veto'
    end

    get 'show_admin', to: 'employees#show_admin'
    get 'admin_profile', to: 'employees#admin_profile'
    post 'dismiss_notifications', to: 'employees#dismiss_notifications'
  end

  # static pages
  get 'about', to: 'static_pages#about'

  root to: redirect('about')
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>" role="alert">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="no-shadow navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'BimaGuide', about_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      onclick="toggleCollapse()">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', about_path, class: 'nav-link active' %>
	</li>
	<% if employee_signed_in? %>
    <li class="nav-item">
      <%= link_to 'Contribute', employee_contributions_path(current_employee), class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Job', employee_jobs_path(current_employee), class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Claim', employee_claims_path(current_employee), class: 'nav-link' %>
    </li>
    <% if show_election? %>
          <li class="nav-item alert-warning">
            <%= link_to 'Pending Elections', employee_elections_path(current_employee), class: 'nav-link alert-link' %>
          </li>
    <% end %>
	<% else %>
    <li class="nav-item">
      <%= link_to 'Donate', donation_services_path, class: 'nav-link active' %>
    </li>
  <% end %>
      </ul>

      <div class="btn-group" role="group">
        <% btn_attn, btn_secondary = 'nav-link ', 'nav-link active' %>
        <% if employee_signed_in? %>
          <%= link_to 'Profile', employee_path(current_employee), class: btn_attn, method: :get %>
          <%= link_to 'Logout', destroy_employee_session_path, class: btn_secondary, method: :delete %>
        <% else %>
          <%= link_to 'Register', new_employee_registration_path, class: btn_attn, method: :get %>
          <%= link_to 'Login', new_employee_session_path, class: btn_secondary %>
        <% end %>
      </div>

    </div>
  </div>
</nav>

<script>
  function toggleCollapse() {
      // bootstrap data toggle not working ~ monkey patch
      let navElem = document.getElementById("navbarSupportedContent");
      let navClass = navElem.className;
      if (navClass.includes("collapsed")) {
          navElem.className = navClass.replace("collapsed", "collapse");
      } else {
          navElem.className = navClass.replace("collapse", "collapsed");
      }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BimaGuide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body class="bg-light text-dark">
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>